### ISSUE TITLE
i really love it but it just looks so bad

### ISSUE THREAD

**Issue by JadeVane** [biji/simplenetspeed#12]
how can i do for it?
![image](https://user-images.githubusercontent.com/34258753/36642363-7a15d162-1a79-11e8-830f-9599135c16d5.png)
what is the end of that? point point point?

**Comment by biji** [comment]
have you tried, middle click to change font size?

**Comment by JadeVane** [comment]
thanks for reply!
i tried it just now,but the result is unsatisfactory,the font size is so small that only keep very close to my screen can i see what it show,is that any other way to solve it?

**Comment by ser** [comment]
Yes, it is the smallest font and yes i logged in / logged out several times already

**Comment by isgroup-srl** [comment]
Yes truncated also for me! To improve readability it would be nice to have a fixed MB/Mb scale as most ADSL/VDSL users are, let's say, 100Mbit down/30Mbit up. In format string lingo `%.2f`.

**Comment by ser** [comment]
but, why closed?

**Comment by JadeVane** [comment]
@ser 

It seems that the owner do not want to deal with it, so I would give up using this extension. I think it is not neccessary to keep it opening for the reason that I give it up, at the same time, the most important thing is the owner give it up.

I am sorry for causing any trouble to you if I close this issue.

**Comment by marcosox** [comment]
The width of the widget is too small and the answer is "make the text smaller"?

wow, just wow
