### ISSUE TITLE
Differentiate between received and transmitted data instead of sum up them in one single value.

### ISSUE THREAD

**Issue by chmercesmoreira** [biji/simplenetspeed#2]
Hello, I'd to suggest a new feature, as the tittle of this issue suggests I want to differentiate between these two data information, I took a look at your code and found out the place in your code where you just sum up these two values in one single value:
https://github.com/biji/simplenetspeed/blob/c5a340aa3c452fdd00bd0127471020f437c8c941/extension.js#L76

**Comment by biji** [comment]
implemented in https://github.com/biji/simplenetspeed/commit/9431cac364d15b6a27c694c875e26af259568310

**Comment by chmercesmoreira** [comment]
Thank you for implementing this new feature, I tested here but the extension is still showing  just one value grouped, what I suggested was something like this:
![Example 1]
(http://i.imgur.com/oYEIwDA.png)
![Example 2]
(http://i.imgur.com/HrGJz5m.png)

**Comment by biji** [comment]
you've to click it to switch different modes :D

**Comment by chmercesmoreira** [comment]
I tried but it didn't change to this mode, I'm going to try it today morning and I'll give you a new feedback.

**Comment by chmercesmoreira** [comment]
OK, now it's working, I think it was a delay between your update submission and the gnome.org server recognizing it. But now I'm getting a weird bug, the arrows are being show as white rectangles and the space intended for the numbers at the left hand side are being shortened:
![Image]
(http://i.imgur.com/80hxmEN.png)
If you want any debug information or informations about my system you can ask me any time.

**Comment by biji** [comment]
I'm not sure what cause this, its only unicode character up and down. Try to change gnome font?

**Comment by chmercesmoreira** [comment]
I'm using this set o fonts:
![Image]
(http://i.imgur.com/JtMyXcs.png)
I'm going to try a new set.

**Comment by chmercesmoreira** [comment]
Maybe this was the change you did that is causing this "bug":
https://github.com/biji/simplenetspeed/commit/9431cac364d15b6a27c694c875e26af259568310#diff-06f1274e40de25abda72d812b1cce86aL97

**Comment by biji** [comment]
yes, im seeing arrows

![image](https://cloud.githubusercontent.com/assets/665559/16791241/2ad6c9b8-48e7-11e6-83e8-95a507913683.png)

**Comment by chmercesmoreira** [comment]
What are the fonts you are using? I'm going to try these fonts.

**Comment by biji** [comment]
It is standard Fedora 24, adwiata, no gnome shell theme

**Comment by chmercesmoreira** [comment]
Adwiata seems to not to be a font but a theme, I tried but with no success, I searched for the unicode id of these characters here: http://xahlee.info/comp/unicode_arrows.html
And the arrows shown there are working (being rendered) properly on my system, so can you substitute the arrows you are using for these two:
↑ and ↓

**Comment by biji** [comment]
ok done, would you please try git version before i release

thanks

**Comment by chmercesmoreira** [comment]
Hello, I tried to test the git version but I could not make it work, I followed this steps:
`git clone https://github.com/biji/simplenetspeed
cp simplenetspeed ~/.local/share/gnome-shell/extensions/simplenetspeed/`
And I restarted the gnome shell, but the extension don't appeared in the gnome tweak tool.

But I think it will work because now I can see the arrows in your code:
![image]
(http://www.auplod.com/u/lopadu82c37.png)

**Comment by chmercesmoreira** [comment]
Thank you, now I'm seeing the arrows, just one more thing, you changed the lines related to download and upload mode, but the single value mode is still using the old invalid character: https://github.com/biji/simplenetspeed/blob/0a198b5b2696eb5292b25d66248c31c6ad8484df/extension.js#L118
Please change it to use the new arrow character as well.

**Comment by chmercesmoreira** [comment]
Other issue, actually a UI issue I think, is the disposition of the values in the dual mode, you are printing the download value in the right side and the upload in the left side, but the correct is the opposite, at least every net speed monitor as I have used until now follow this rule. I don't know if it was your choice, but if it was, then leaves the way it is.

**Comment by biji** [comment]
Ok good catch.. I'll reverse that

**Comment by chmercesmoreira** [comment]
Thank you, you just forgot to change the line related to the single mode (one single value): https://github.com/biji/simplenetspeed/blob/b3f2f9c8bedd99f23717664bf58027a824b720d6/extension.js#L118

And I got the last update installing the last commit from git, it seens that the version available at gnome.org: https://extensions.gnome.org/extension/1085/simple-net-speed/
is not up to date.

**Comment by biji** [comment]
I've submit to extensions.gnome.org but the admin too slow to approve it. 

btw for both up and down char: ⮁ actually it is only one character. would you please suggest similiar char (one character) which displayed correctly in your system

thanks

**Comment by chmercesmoreira** [comment]
Ok, I thought the updates were automatically submitted to the server in the same way the Arch Linux User Repository AUR works.
Here is the character you are asking for: ⇅

I think the changes you made using these new characters I suggested were good changes because even in my android smartphone I could not see the old characters, and now I can.

Thank you for listening my suggestions, good work, and now your extension is very usable.
