### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by LittleControl** [biji/simplenetspeed#23]
No property x_fill on StBin

**Comment by prateekmedia** [comment]
Which version of gnome shell you are using?

 if you dont  know then type "gnome-shell --version" in terminal

**Comment by wayne9499** [comment]
3.38.1

**Comment by LittleControl** [comment]
- When I use the web page to install, it will fail, and the log will prompt "No property x_fill on StBin"  
- version: `GNOME Shell 3.38.1`
- But when I manually copy the file under `~/.local/share/gnome-shell/extensions` and restart it, it is normal, which is very strange
- Now I can install and update normally on the webpage
