### ISSUE TITLE
No data shown

### ISSUE THREAD

**Issue by jrie** [biji/simplenetspeed#3]
On my system Debian Stretch there is no data shown by default.

It seems the regular expression to read out the data from "line" (proc/net/dev) is, in reason of previous spaces before the device name, off by one.

But with this change, it does work fields[1] instead of fields[0] and so forth:
```
            line = String(line);
            let fields = line.split(/\W+/);
    
            if (fields.length<=2) break;
            
            if (fields[1] != "lo" && !isNaN(parseInt(fields[2]))) {
                count = count + parseInt(fields[2]) + parseInt(fields[10]);
                countUp = countUp + parseInt(fields[10]);
            }
```

Perhaps the split regular expression should ignore previous whitespace?

**Comment by biji** [comment]
can you post raw output of /proc/net/dev

**Comment by jrie** [comment]
Sure.

Here is the file:
[dev.txt](https://github.com/biji/simplenetspeed/files/388969/dev.txt)

**Comment by biji** [comment]
this should be fixed now, i have submit to extensions.gnome.org (but wait admin to approve)
or try git clone and replace contents in  
/home/USERNAME/.local/share/gnome-shell/extensions/simplenetspeed@biji.extension
