### ISSUE TITLE
Top bar button refresh abnormally.

### ISSUE THREAD

**Issue by STARRY-S** [biji/simplenetspeed#32]
I run into this problem on my Arch Linux with the latest version of this extension installed.

https://user-images.githubusercontent.com/41445339/123545593-692e4c80-d78b-11eb-90ff-85abb850410b.MOV

> PS: I changed the `refreshTime` to 1 second in order to better show this problem.
> And the gnome shell version is 40.2

**Comment by STARRY-S** [comment]
After I commented all `width` property in `stylesheet.css`, it run into normal.
It seems like a GNOME bug but I do not know how to fix it.

**Comment by biji** [comment]
removing `width` is workaround, but resized too often

**Comment by prateekmedia** [comment]
> removing `width` is workaround, but resized too often

You can use min-width property of css, instead of regular width and it can even be less like 5.5em per element after that it will resize to fit. 

This is what I used in my fork [netspeedsimplified](https://github.com/prateekmedia/netspeedsimplified) and it worked like charm.

**Comment by JoalpaLe** [comment]
> You can use min-width property of css, instead of regular width and it can even be less like 5.5em per element after that it will resize to fit.

I second this. This fixed the issue immediately.

**Comment by prateekmedia** [comment]
@JoalpaLe Maybe you can create the pull request as I see that @biji only does bare maintenance of this extension.

**Comment by biji** [comment]
@JoalpaLe when resizing, all extensions on left will move too much, thats why I prefer static width. For example 0 B to 1000 MB
