### ISSUE TITLE
Not working on GNOME 42.4

### ISSUE THREAD

**Issue by Rizwan-Hasan** [biji/simplenetspeed#37]
I'm using Manjaro which has Gnome 42.4 and running on x11. Got some weird error.

![image](https://user-images.githubusercontent.com/16849373/192533917-272275bf-37dc-4d9a-8212-d053d3786639.png)

**Comment by biji** [comment]
thanks for reporting, should be fix in https://github.com/biji/simplenetspeed/commit/9f6d11e9caccda74368dd9af44bc60157546e09e

**Comment by Rizwan-Hasan** [comment]
Thanks for the fix. Now It's working.
